version: "3.9"

services:
  web:
    build: 
      context: ./DjangoApp
      dockerfile: Dockerfile
    command: /bin/sh -c "entrypoint.sh"
    ports:
      - "80:8000"
    env_file:
      - ./DjangoApp/.env