# Generated by Django 3.1.5 on 2021-02-15 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='key',
            fields=[
                ('key_id', models.AutoField(primary_key=True, serialize=False)),
                ('key_type_char', models.CharField(max_length=15, unique=True, verbose_name='Key')),
            ],
        ),
        migrations.CreateModel(
            name='session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300, unique=True, verbose_name='Session Name')),
                ('date', models.DateField(verbose_name='Session Date')),
                ('youtube_url', models.URLField(blank=True, verbose_name='Session Youtube URL')),
            ],
        ),
        migrations.CreateModel(
            name='tune_type',
            fields=[
                ('tune_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('tune_type_char', models.CharField(max_length=50, unique=True, verbose_name='Tune Type')),
            ],
        ),
        migrations.CreateModel(
            name='tune',
            fields=[
                ('tune_id', models.AutoField(primary_key=True, serialize=False)),
                ('name1', models.CharField(max_length=300, verbose_name='Tune Name')),
                ('name2', models.CharField(blank=True, max_length=300, verbose_name='Alternate Name')),
                ('name3', models.CharField(blank=True, max_length=300, verbose_name='Alternate Name')),
                ('name4', models.CharField(blank=True, max_length=300, verbose_name='Alternate Name')),
                ('the_session_url', models.URLField(blank=True)),
                ('tune_info', models.CharField(blank=True, max_length=300, verbose_name='Information about the tune')),
                ('tune_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.tune_type', verbose_name='Tune Type')),
            ],
        ),
        migrations.CreateModel(
            name='played_tune_group',
            fields=[
                ('played_tune_group_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_order_num', models.IntegerField(verbose_name='Order of Tune Group')),
                ('start_time', models.DurationField(verbose_name='Start Time of Group\nin Youtube Recording')),
                ('end_time', models.DurationField(verbose_name='End Time of Group\nin Youtube Recording')),
                ('offertory', models.BooleanField(verbose_name='Is tune group an offertory?')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.session', verbose_name='Session')),
            ],
        ),
        migrations.CreateModel(
            name='played_tune',
            fields=[
                ('played_tune_id', models.AutoField(primary_key=True, serialize=False)),
                ('group_order_num', models.IntegerField(verbose_name='Order tune was played in tune group.')),
                ('add_info', models.CharField(blank=True, max_length=300, verbose_name='Additional information about the tune for this perticular time                                it was played')),
                ('key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Key', to='session.key', verbose_name='Key of Tune')),
                ('played_tune_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.played_tune_group', verbose_name='Played Tune Group')),
                ('tune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.tune', verbose_name='Tune Name')),
            ],
        ),
        migrations.CreateModel(
            name='name_yer_tune',
            fields=[
                ('name_yer_tune_id', models.AutoField(primary_key=True, serialize=False)),
                ('youtube_teaching_url', models.URLField(verbose_name='#nameyertune Youtube Teaching URL')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.session', verbose_name='Session')),
                ('tune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.tune', verbose_name='Tune Name')),
            ],
        ),
    ]
