# Generated by Django 3.1.5 on 2021-02-21 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='name_yer_tune',
            name='youtube_teaching_url',
            field=models.URLField(verbose_name='#nameyertune Youtube Teaching Embeded URL'),
        ),
        migrations.CreateModel(
            name='tune_of_the_month',
            fields=[
                ('tune_of_the_month_id', models.AutoField(primary_key=True, serialize=False)),
                ('published_date', models.DateField(verbose_name='Published Date')),
                ('youtube_teaching_url', models.URLField(verbose_name='Tune of the Month Embeded URL')),
                ('tune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.tune', verbose_name='Tune Name')),
            ],
        ),
    ]
