# Generated by Django 3.2.6 on 2021-10-15 15:10

from django.db import migrations, models
from django.db.migrations.operations.models import RenameModel
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_alter_name_yer_tune_session'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tune_type',
            new_name='TuneType',
        ),
        migrations.RenameModel(
            old_name='played_tune_group',
            new_name='PlayedTuneGroup',
        ),
        migrations.RenameModel(
            old_name='played_tune',
            new_name='PlayedTune',
        ),
        migrations.RenameModel(
            old_name='name_yer_tune',
            new_name='NameYerTune',
        ),
        migrations.RenameModel(
            old_name='tune_of_the_month',
            new_name='TuneOfTheMonth',
        ),
    ]
