# Generated by Django 3.2.6 on 2021-10-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_auto_20211015_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playedtune',
            name='add_info',
            field=models.CharField(blank=True, max_length=300, verbose_name='Additional information about the Tune for this perticular time                                it was played'),
        ),
        migrations.AlterField(
            model_name='playedtune',
            name='group_order_num',
            field=models.IntegerField(verbose_name='Order Tune was played in Tune group.'),
        ),
        migrations.AlterField(
            model_name='playedtunegroup',
            name='offertory',
            field=models.BooleanField(verbose_name='Is Tune group an offertory?'),
        ),
        migrations.AlterField(
            model_name='tune',
            name='tune_info',
            field=models.CharField(blank=True, max_length=300, verbose_name='Information about the Tune'),
        ),
    ]
