# Generated by Django 3.2.4 on 2021-11-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0005_auto_20211015_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='name',
            field=models.CharField(max_length=300, verbose_name='Session Name'),
        ),
    ]
