# Generated by Django 3.2.4 on 2022-01-11 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_alter_session_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tune',
            name='common_core',
            field=models.BooleanField(default=False, verbose_name='Common Core Tune'),
        ),
    ]
