# Generated by Django 3.2.4 on 2022-01-11 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0007_tune_common_core'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShannonTeachingBookRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Name of Shannon Teaching Book')),
                ('resource_url', models.URLField(verbose_name='Resource URL for tune')),
            ],
        ),
        migrations.AddField(
            model_name='tune',
            name='shannon_teaching_book_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='session.shannonteachingbookref', verbose_name='Session'),
        ),
    ]
