# Generated by Django 3.2.4 on 2022-01-11 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0008_auto_20220111_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='playedtunegroup',
            name='teaching',
            field=models.BooleanField(default=False, verbose_name='Is Tune a Teaching Set?'),
        ),
        migrations.AlterField(
            model_name='tune',
            name='shannon_teaching_book_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='session.shannonteachingbookref', verbose_name='Shannon Teaching Reference'),
        ),
    ]
