# Generated by Django 4.2.30 on 2026-04-30 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0009_auto_20220111_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playedtunegroup',
            name='end_time',
            field=models.DurationField(blank=True, null=True, verbose_name='End Time of Group\nin Youtube Recording'),
        ),
    ]
