name: Deployment From Github To AWS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@master
      
      - name: Create env file
        run: |
          touch DjangoApp/.env
          echo "# Set environment variables" >> DjangoApp/.env
          echo "SECRET_KEY = ${{ secrets.SECRET_KEY }}" >> DjangoApp/.env
          echo "DEBUG = ${{ secrets.DEBUG }}" >> DjangoApp/.env
          echo "ALLOWED_HOSTS = ${{ secrets.ALLOWED_HOSTS }}" >> DjangoApp/.env
          cat DjangoApp/.env
      
      # Zip All Files to deploy to AWS
      - name: Generate Deployment Package
        working-directory: ./DjangoApp #Only Need Files In DjangoApp Folder
        run: zip -r deploy.zip . -x '*.git*'
      
      # Get Timestamp to add to docker image
      - name: Get timestamp
        uses: gerred/actions/current-time@master
        id: current-time
        
      - name: Run string replace
        uses: frabert/replace-string-action@master
        id: format-time
        with:
          pattern: '[:\.]+'
          string: "${{ steps.current-time.outputs.time }}"
          replace-with: '-'
          flags: 'g'
      
      # Deploy to AWS ElasticBeanStalk
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v14
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Prod
          environment_name: Prod-env
          version_label: "djangobeantest-${{ steps.format-time.outputs.replaced }}"
          region: us-east-1
          wait_for_environment_recovery: 60
          deployment_package: DjangoApp/deploy.zip